### ISSUE TITLE
How to calculate the distance between different classes within one dataset?

### ISSUE THREAD

**Issue by zhangdong1992** [kheyer/OTDD#1]
Hi, how can I calculate the distance between different classes within one dataset?

**Comment by kheyer** [comment]
To start lets say we have our dataset formatted as two numpy arrays X and Y. X is a `(n,f)` array (number of datapoints by features) and Y is a `(n,)` array of integer class labels where there are `c` distinct classes in the dataset.

Make the dataset

```
data = ArrayDataset(x, y)
```

Define the distance function and cost function

```
distance_function = POTDistance(distance_metric='euclidean')
cost_function = SinkhornCost(distance_function, 0.02)
```

To get the class distances, we can do the following

```
outputs = cost_function.label_distances(data.features, data.features, 
                                              data.labels, data.labels)
class_distances, class_x_dict, class_y_dict = outputs
```

`class_distances` is the `(c,c)` matrix of class to class distances within the dataset. `class_x_dict` and `class_y_dict` map the index values of `class_distances` to the label values in `y`.

If you want to calculate the coupling and OTDD cost within the dataset, you can do the following

```
outputs = cost_function.distance_with_labels(data.features, data.features, 
                                              data.labels, data.labels, mask_diagonal=True)
cost, coupling, OTDD_matrix, class_distances, class_x_dict, class_y_dict = outputs
```

In the above code, we calculate the OTDD distance between the dataset and itself. Passing `mask_diagonal=True` masks the diagonal of the distance matrix to ensure elements don't get coupled to themselves. From the outputs, `class_distances`, `class_x_dict`, `class_y_dict` are the same as the outputs from `cost_function.label_distances`. `cost`, `coupling` and `OTDD_matrix` are the OTDD cost, coupling matrix and distance matrix for the OTDD calculation.

Also some notes on performance. If the dataset is large, we can approximate OT distances with a Gaussian distance, which is significantly faster and less memory intensive.

```
# computes just class to class distances with Gaussian approximation
outputs = cost_function.label_distances(data.features, data.features, 
                                              data.labels, data.labels, gaussian=True)

# Gaussian class to class distances, still solves full OT problem over the dataset
outputs = cost_function.distance_with_labels(data.features, data.features, 
                                              data.labels, data.labels, mask_diagonal=True,
                                              gaussian_class_distance=True)

# Gaussian class to class distances, solves the dataset distance using the `(c,c)` class distance matrix
# rather than the `(n,n)` dataset distance matrix
outputs = cost_function.distance_with_labels(data.features, data.features, 
                                              data.labels, data.labels, mask_diagonal=True,
                                              gaussian_class_distance=True,  gaussian_data_distance=True)
```

If you have KeOps set up you can also use KeOps online routines which have a lower memory footprint

```
data = TensorDataset(torch.from_numpy(x).float(), torch.from_numpy(y).long())

distance_online = EuclideanOnline()
routine_tensorized = SinkhornOnline(distance_online)
cost_online = SamplesLossOnline(routine_tensorized)

# class distances
outputs = cost_online.label_distances(data.features, data.features,
                                     data.labels, data.labels)

# full OTDD calculation
outputs = cost_online.distance_with_labels(data.features, data.features,
                                     data.labels, data.labels)
```

**Comment by shudong-zhang** [comment]
Thank you very much for your detailed answer. I got it.
